name: to-do app linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        if: always()
        run: npm run build
      - name: linting typescript
        if: always()
        run: npm run lint
      - name: testing
        if: always()
        run: npm run test
